version: "3.7"

x-tg-client: &tg-client
  image: ${REGISTRY_URL}tg-client:dev
  restart: always

services:
  database:
    image: postgres:13.4
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 6s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_PASSWORD: ${DB_PASS:?}
      TZ: Europe/Moscow
    volumes: 
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - '${DB_PORT:-5432}:5432'

  db_seed:
    image: ${REGISTRY_URL}database-seed:develop
    build:
      context: ./db_init
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_USER}
      DB_HOST: database
    depends_on:
      database:
        condition: service_healthy
   
  tg-client1:
    <<: *tg-client
    environment:
      - SESSION=${SESSION_1:?}
      - API_ID=${API_ID_1:?}
      - API_HASH=${API_HASH_1:?}
      - PHONE=null
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_HOST=database
    volumes:
      - ./sessions/${SESSION_1}.session:/home/app/${SESSION_1}.session
      - ./logs/${SESSION_1}:/home/app/logs
      - ./data/${SESSION_1}:/home/app/data
    depends_on:
      db_seed:
        condition: service_completed_successfully
      database:
        condition: service_healthy
   
  tg-client2:
    <<: *tg-client
    environment:
      - SESSION=${SESSION_2:?}
      - API_ID=${API_ID_2:?}
      - API_HASH=${API_HASH_2:?}
      - PHONE=null
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_HOST=database
    volumes:
      - ./sessions/${SESSION_2}.session:/home/app/${SESSION_2}.session
      - ./logs/${SESSION_2}:/home/app/logs
      - ./data/${SESSION_2}:/home/app/data
    depends_on:
      db_seed:
        condition: service_completed_successfully
      database:
        condition: service_healthy

  tg-client3:
    <<: *tg-client
    environment:
      - SESSION=${SESSION_3:?}
      - API_ID=${API_ID_3:?}
      - API_HASH=${API_HASH_3:?}
      - PHONE=null
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_HOST=database
    volumes:
      - ./sessions/${SESSION_3}.session:/home/app/${SESSION_3}.session
      - ./logs/${SESSION_3}:/home/app/logs
      - ./data/${SESSION_3}:/home/app/data
    depends_on:
      db_seed:
        condition: service_completed_successfully
      database:
        condition: service_healthy
   
  tg-client4:
    <<: *tg-client
    environment:
      - SESSION=${SESSION_4:?}
      - API_ID=${API_ID_4:?}
      - API_HASH=${API_HASH_4:?}
      - PHONE=null
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_HOST=database
    volumes:
      - ./sessions/${SESSION_4}.session:/home/app/${SESSION_4}.session
      - ./logs/${SESSION_4}:/home/app/logs
      - ./data/${SESSION_4}:/home/app/data
    depends_on:
      db_seed:
        condition: service_completed_successfully
      database:
        condition: service_healthy
   
  tg-client5:
    <<: *tg-client
    environment:
      - SESSION=${SESSION_5:?}
      - API_ID=${API_ID_5:?}
      - API_HASH=${API_HASH_5:?}
      - PHONE=null
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_HOST=database
    volumes:
      - ./sessions/${SESSION_5}.session:/home/app/${SESSION_5}.session
      - ./logs/${SESSION_5}:/home/app/logs
      - ./data/${SESSION_5}:/home/app/data
    depends_on:
      db_seed:
        condition: service_completed_successfully
      database:
        condition: service_healthy
   
  tg-client6:
    <<: *tg-client
    environment:
      - SESSION=${SESSION_6:?}
      - API_ID=${API_ID_6:?}
      - API_HASH=${API_HASH_6:?}
      - PHONE=null
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_HOST=database
    volumes:
      - ./sessions/${SESSION_6}.session:/home/app/${SESSION_6}.session
      - ./logs/${SESSION_6}:/home/app/logs
      - ./data/${SESSION_6}:/home/app/data
    depends_on:
      db_seed:
        condition: service_completed_successfully
      database:
        condition: service_healthy
   
  tg-client7:
    <<: *tg-client
    environment:
      - SESSION=${SESSION_7:?}
      - API_ID=${API_ID_7:?}
      - API_HASH=${API_HASH_7:?}
      - PHONE=null
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_HOST=database
    volumes:
      - ./sessions/${SESSION_7}.session:/home/app/${SESSION_7}.session
      - ./logs/${SESSION_7}:/home/app/logs
      - ./data/${SESSION_7}:/home/app/data
    depends_on:
      db_seed:
        condition: service_completed_successfully
      database:
        condition: service_healthy
   
  tg-client8:
    <<: *tg-client
    environment:
      - SESSION=${SESSION_8:?}
      - API_ID=${API_ID_8:?}
      - API_HASH=${API_HASH_8:?}
      - PHONE=null
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_HOST=database
    volumes:
      - ./sessions/${SESSION_8}.session:/home/app/${SESSION_8}.session
      - ./logs/${SESSION_8}:/home/app/logs
      - ./data/${SESSION_8}:/home/app/data
    depends_on:
      db_seed:
        condition: service_completed_successfully
      database:
        condition: service_healthy
   
  tg-client9:
    <<: *tg-client
    environment:
      - SESSION=${SESSION_9:?}
      - API_ID=${API_ID_9:?}
      - API_HASH=${API_HASH_9:?}
      - PHONE=null
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_HOST=database
    volumes:
      - ./sessions/${SESSION_9}.session:/home/app/${SESSION_9}.session
      - ./logs/${SESSION_9}:/home/app/logs
      - ./data/${SESSION_9}:/home/app/data
    depends_on:
      db_seed:
        condition: service_completed_successfully
      database:
        condition: service_healthy
   
  tg-client10:
    <<: *tg-client
    environment:
      - SESSION=${SESSION_10:?}
      - API_ID=${API_ID_10:?}
      - API_HASH=${API_HASH_10:?}
      - PHONE=null
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_HOST=database
    volumes:
      - ./sessions/${SESSION_10}.session:/home/app/${SESSION_10}.session
      - ./logs/${SESSION_10}:/home/app/logs
      - ./data/${SESSION_10}:/home/app/data
    depends_on:
      db_seed:
        condition: service_completed_successfully
      database:
        condition: service_healthy
   
  tg-client12:
    <<: *tg-client
    environment:
      - SESSION=${SESSION_12:?}
      - API_ID=${API_ID_12:?}
      - API_HASH=${API_HASH_12:?}
      - PHONE=null
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_HOST=database
    volumes:
      - ./sessions/${SESSION_12}.session:/home/app/${SESSION_12}.session
      - ./logs/${SESSION_12}:/home/app/logs
      - ./data/${SESSION_12}:/home/app/data
    depends_on:
      db_seed:
        condition: service_completed_successfully
      database:
        condition: service_healthy

volumes:
  postgres-db-volume:
