version: "3.7"

x-tg-client: &tg-client
  image: ${REGISTRY_URL}tg-client:dev
  restart: always

services:
  database:
    image: postgres:13.4
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 6s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_PASSWORD: ${DB_PASS:?}
      TZ: Europe/Moscow
    volumes: 
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - '${DB_PORT:-5432}:5432'

  db_seed:
    image: ${REGISTRY_URL}database-seed:develop
    build:
      context: ./db_init
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_USER}
      DB_HOST: database
    depends_on:
      database:
        condition: service_healthy
   
  tg-client1:
    <<: *tg-client
    environment:
      - SESSION=${SESSION_1:?}
      - API_ID=${API_ID_1:?}
      - API_HASH=${API_HASH_1:?}
      - PHONE=null
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_HOST=database
    volumes:
      - ./sessions/${SESSION_1}.session:/home/app/${SESSION_1}.session
      - ./logs/${SESSION_1}:/home/app/logs
      - ./data/${SESSION_1}:/home/app/data
    depends_on:
      db_seed:
        condition: service_completed_successfully


volumes:
  postgres-db-volume:
