version: "3.7"

services:
  database:
    image: postgres:13.4
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 6s
      retries: 5
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      TZ: Europe/Moscow
    volumes: 
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - '${DB_PORT:-5432}:5432'

  mqueue:
    image: rabbitmq:3.9.7-management
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_MQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_MQ_PASS}
    ports:
      - '${RABBITMQ_MONITORING_PORT:-15672}:15672'
      - '${RABBITMQ_PORT:-5672}:5672'
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@rabbitmq

  db_seed:
    image: ${REGISTRY_URL}database-seed
    build:
      context: ./db_init
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_DATABASE: ${DB_USER}
      DB_HOST: database
    depends_on:
      database:
        condition: service_healthy

volumes:
  postgres-db-volume:
  rabbitmq-data: